export const ADD_PRODUCT_ITEM = 'ADD_PRODUCT_ITEM';
export const SAVE_PRODUCT_ITEM = 'SAVE_PRODUCT_ITEM';
export const SAVE_PROMO_PRODUCT_ITEM = 'SAVE_PROMO_PRODUCT_ITEM';
export const RESET_STATE_PRODUCT_ITEM = 'RESET_STATE_PRODUCT_ITEM';
