export const ADD_SERVICE_ITEM = 'ADD_SERVICE_ITEM';
export const DELETE_SERVICE_ITEM = 'DELETE_SERVICE_ITEM';
export const SAVE_SERVICE_ITEM = 'SAVE_SERVICE_ITEM';
export const CHANGE_STATE_SERVICE_ITEM = 'CHANGE_STATE_SERVICE_ITEM';
export const EDIT_SERVICE_ITEM = 'EDIT_SERVICE_ITEM';
export const RESET_STATE_SERVICE_ITEM = 'RESET_STATE_SERVICE_ITEM';